name: CI + Deploy
on:
  pull_request:
    branches: ["**"]
  push:
    branches-ignore:
      - 'ci/failure-*'
  workflow_dispatch:
permissions:
  actions: read
  contents: write
  pull-requests: write
  issues: write
jobs:
  ci:
    name: Reusable CI
    uses: ds-engageiq/workflow/.github/workflows/reusable-ci.yml@main
    with:
      go-enabled: false
      go-version: '1.22.x'
      go-workdir: '.'
      golangci-lint-enabled: true
      govulncheck-enabled: true
      node-enabled: false
      node-autodetect: true
      migrations-enabled: false
      migrations-db-type: 'mysql'
      mysql-image: 'mysql:8'
      mysql-root-password: 'root'
      mysql-database: 'testdb'
      migrations-sql-glob: 'migrations/*.sql'
      docker-build-enabled: false
      docker-context: '.'
      dockerfile: 'Dockerfile'
      shellcheck-enabled: true
    secrets: inherit
  deploy:
    name: Deploy on CI success
    needs: ci
    if: ${{ needs.ci.result == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ds-engageiq/workflow/.github/workflows/ultra-safe-deploy-reusable.yml@main
    with:
      environment: staging
      ref: ${{ github.sha }}
      workdir: .
      script: deploy.sh
    secrets: inherit
